# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

<<<<<<< HEAD
title: Machine Learning with Graph
author: Soheila Ashkezari-T.
logo: logo.png
copyright: "© Copyright 2025"

=======
title: Machine Learning With Graph
author: Soheila Ashkezari-T.
logo: logo.png
copyright: "© Copyright 2025, Soheila Ashkezari-T."
>>>>>>> dd60f64 (chap 1 -4 updated)
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
<<<<<<< HEAD
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
=======
  url: https://s-ashkezari.github.io/MLG/intro.html  # Online location of your book
>>>>>>> dd60f64 (chap 1 -4 updated)
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
